const products = [
    {
        id: 0,
        name: "Handmade Hair Band",
        price: 5,
        instock: 20,
        imgSrc: "./image/accessories1.jpg",
    },
    {
        id: 1,
        name: "Carpet",
        price: 80,
        instock: 100,
        imgSrc: "./image/carpet1.jpg",
    },
    {
        id: 2,
        name: "Vintage Tea Cups",
        price: 40,
        instock: 30,
        imgSrc: "./image/pottery2.jpg",
    },
    {
        id: 3,
        name: "Vintage Lamp",
        price: 90,
        instock: 10,
        imgSrc: "./image/lamp.jpg",
    },
    {
        id: 4,
        name: "Pochette",
        price: 10,
        instock: 100,
        imgSrc: "./image/accessories2.jpg",
    },
    {
        id: 5,
        name: "Painting",
        price: 35,
        instock: 10,
        imgSrc: "./image/painting1.jpg",
    },
    {
        id: 6,
        name: "Pottery Plates",
        price: 15,
        instock: 50,
        imgSrc: "./image/potteryPlat.jpg",
    },
    {
        id: 7,
        name: "Chinese Parapluie",
        price: 12,
        instock: 10,
        imgSrc: "./image/paraapluiechinese.jpg",
    },
    {
        id: 8,
        name: "Vintage Radio",
        price: 200,
        instock: 5,
        imgSrc: "./image/radioVintage.jpg",
    },
    {
        id: 9,
        name: "Healing Cristals",
        price: 35,
        instock: 100,
        imgSrc: "./image/pieres.jpg",
    },
    {
        id: 10,
        name: "Pottery Plate",
        price: 30,
        instock: 10,
        imgSrc: "./image/potteryPlat1.jpg",
    },
    {
        id: 11,
        name: "Paint",
        price: 20,
        instock: 10,
        imgSrc: "./image/painting2.jpg",
    },
];